### ISSUE TITLE
Feature: User can view gallery

### ISSUE THREAD

**Issue by RobACurtis** [RobACurtis/final-project#1]
## ⚙️ Feature
> ##### What capability will users have when this feature is merged?
When the user comes to the web applications home page, there will be a button the user can click to explore a collection of images from the applications users.

## 📐 Functionality
> ##### A description of how the application will work from the perspective of the user.
When the user goes to the home page, they will see a button to click in order to explore a gallery of images from varying users of the app. On the explore page, the surfr logo will be a link back to the home page. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-05-30 at 10 56 51 AM](https://user-images.githubusercontent.com/96838616/171041619-cdd2f9df-8fae-45df-a2a7-0df45d817af3.png)

![Screen Shot 2022-05-30 at 10 57 12 AM](https://user-images.githubusercontent.com/96838616/171041637-e2f6982b-eb59-466c-992d-93e06a40b35e.png)
![Screen Shot 2022-05-30 at 10 57 02 AM](https://user-images.githubusercontent.com/96838616/171041649-cab78ab1-c7d1-452f-a401-bbc1c859588d.png)

![Screen Shot 2022-05-30 at 10 57 24 AM](https://user-images.githubusercontent.com/96838616/171041676-1d6464fe-8dcb-4afa-81c4-5e8c0f40f7ee.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Update `data.sql` to ...
- [x] 	there will be 2 example users
- [x] there will be 10 images (5 assigned to each user)
- [x] there will be 4 images specifically for the home page 
	

### ☁️ Server

- [x] Update `server/index.js` to ...
- [x] 	the server needs to be able to respond to get requests from the client
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client
- [x] set up a styles.css and link it to the html page
- [x] link bootstrap into html

### ⚡ Client

- [x] Create a component to be the home page
- [x] send a request for 4 images to be the background images for the home page
- [x] the images need an interval of 5 seconds on rotation
- [x] implement a button with the text content explore
- [x] create a component to be the explore page.
- [x] when the button on the home page is pressed it will....
- [x] send a request for gallery images
- [x]  load the explore page with the images when the server responds 
- [x] the surfr logo will be a link back to the home page.

### 🧑‍⚕️ Clean Up

- [x] ... 
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
