### ISSUE TITLE
Feature: User can delete a photo from their gallery

### ISSUE THREAD

**Issue by RobACurtis** [RobACurtis/final-project#10]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?
The user can delete an image they uploaded to their gallery.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
The user will have the capability to click on a photo from their gallery where they will see either a close button to exit the larger image view, or a trash can. If they click the trash a modal will open to ask them to confirm they wish to delete the image. They can click cancel to leave the modal, or confirm to delete the image. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-05-30 at 12 34 55 PM](https://user-images.githubusercontent.com/96838616/171051399-a2fd4270-a462-4b5c-899c-f94d7b0b135b.png)
![Screen Shot 2022-05-30 at 12 35 10 PM](https://user-images.githubusercontent.com/96838616/171051402-83d2a9e6-593f-4420-accb-1b15ba43998c.png)
![Screen Shot 2022-05-30 at 12 35 48 PM](https://user-images.githubusercontent.com/96838616/171051404-404f6ce2-e8fb-4b97-912d-a51ec9dad059.png)
![Screen Shot 2022-05-30 at 12 35 02 PM](https://user-images.githubusercontent.com/96838616/171051413-7a9bc07c-22cd-410b-9464-29c0c13acf4a.png)
![Screen Shot 2022-05-30 at 12 35 29 PM](https://user-images.githubusercontent.com/96838616/171051419-c7a32fc1-c7eb-46be-af68-b106f840d0a7.png)
![Screen Shot 2022-05-30 at 12 35 59 PM](https://user-images.githubusercontent.com/96838616/171051422-e422f34c-f539-4d91-8360-b3ec20900bbc.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to ...
- [x] have a route for a delete request
- [x] the user needs to be authorized
- [x] the user id needs to match of the user id of the photo
- [x] query the database to delete the photoId where photo id equals photo Id
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] update the photostream component to ...
- [x] check if the photo the user is viewing belongs to the user
- [x] if it does, they will have a button for the trashcan to click
- [x] Create a modal to be the delete modal/
- [x] it needs to have a cancel button and sit on top of everything
- [x] the cancel button will close the modal
- [x] the delete button will send the request to the server to delete.
- [x] once the delete button is pressed, the photo will be removed from the page and no longer visible.

### 🧑‍⚕️ Clean Up

- [x] Make sure that if the user deletes all of their photos, the photostream will return "you have no photos". 
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
