### ISSUE TITLE
Feature: User can click a single image to view it full screen

### ISSUE THREAD

**Issue by RobACurtis** [RobACurtis/final-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?
User will be able to click on an image and see it in full screen.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user can explore a gallery of images and they will be able to click an image to expand it to see it full screen. There will be a button to close out of the fullscreen view and resume exploration of the gallery. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-05-30 at 11 06 02 AM](https://user-images.githubusercontent.com/96838616/171042525-18314a02-0744-4100-a165-5bc1ce26ce12.png)
![Screen Shot 2022-05-30 at 11 06 17 AM](https://user-images.githubusercontent.com/96838616/171042531-508b573e-25de-4536-a09c-75a2ad25804d.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ⚡ Client

- [x] Update the explore page to ...
- [x] give each image a click event listener
- [x] when a particular image in the gallery is clicked, a modal will appear
- [x] make a new component for image modal
- [x] create a dark background overlay in CSS
- [x] create a new image with the source of the event target image
- [x] the image needs to have its original size and will take up much of the viewport on mobile and a large portion on desktop (refer to figma)
- [x] within the modal, create a font awesome icon to close out of the modal
- [x] when the icon is clicked, the modal will disappear and the user can continue to browse the gallery and click on 
-another image

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
