### ISSUE TITLE
Feature: User can log out 

### ISSUE THREAD

**Issue by RobACurtis** [RobACurtis/final-project#29]
## ⚙️ Feature

User can log out of their account.

## 📐 Functionality
There will be a button in the navbar for the user to click. When it is clicked, the user will be redirected to the home page and logged out.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
![Screen Shot 2022-06-22 at 9 11 14 AM](https://user-images.githubusercontent.com/96838616/175081065-61553608-091e-4b35-8e0c-09826dfb026c.png)
![Screen Shot 2022-06-22 at 9 11 25 AM](https://user-images.githubusercontent.com/96838616/175081089-71c9df84-93ad-4db1-bcde-e9c5611c1644.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ⚡ Client

- [x] Update navbar component to....
- [x] have a hidden menu that will be unhidden when icon is pressed.
- [x] the menu will have two items, log out and view profile
- [x] view profile will trigger hash change to profile page
- [x] log out will trigger a method in app.jsx
- [x] method needs to remove token from local storage and restore application to logout state. 

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
