### ISSUE TITLE
Feature: User can toggle between explore images and explore user profiles

### ISSUE THREAD

**Issue by RobACurtis** [RobACurtis/final-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?
Users will be able to see a list of user profiles and toggle between the user profile page and explore images gallery page. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

While the user is on the explore page, there will be a navbar to toggle between "Photostream" and "People" the user can click either one to see a gallery of images or a list of user profiles. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-05-30 at 11 24 36 AM](https://user-images.githubusercontent.com/96838616/171044516-2e42ba64-b4cd-4b44-9eb4-8bfc734b7106.png)

![Screen Shot 2022-05-30 at 11 25 16 AM](https://user-images.githubusercontent.com/96838616/171044556-d9cdfaec-d92d-477f-b40a-7b2aa90b95a9.png)

![Screen Shot 2022-05-30 at 11 25 31 AM](https://user-images.githubusercontent.com/96838616/171044575-54de2157-fa46-4d1b-8f78-2588afc22d5f.png)
![Screen Shot 2022-05-30 at 11 25 43 AM](https://user-images.githubusercontent.com/96838616/171044581-ee41d98d-f6b8-4220-a79d-dbed4aaf3fc2.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to ...
- [x] respond to get requests for users
- [x] return users first name, last name, email, profile photo from the database
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] remove the code from explore page having to do with photos and create a component to import to the explore page.
- [x] create a component for explore people
- [x] this component will need to fetch for the user data
- [x] it will create bootstrap cards for each user received and display them on the explore people component in a list, using the map method.
- [x] the explore page will return photos by default.
- [x] in explore page implement a second navbar to toggle between photos and users.
- [x] create two a tags one named photostream, the second named people to toggle between images and users.
- [x] depending on state, the active component in the second navbar will be underlined blue.
- [x] implement an a tag in the top navbar for the explore page. 

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
