### ISSUE TITLE
Feature: User can click their profile image to view their profile

### ISSUE THREAD

**Issue by RobACurtis** [RobACurtis/final-project#30]
## ⚙️ Feature

User can click their profile image to view their profile

## 📐 Functionality

Instead of an icon in the navbar, the user will be able to see their photograph. When they click it, it will take them to their profile page.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` sign-in route to select profilePhotoUrl
- [x] send with payload
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Update app.jsx to store profile photo imageURL in the state with user
- [x] update navbar component to have an img element instead of i tag
- [x] img element source needs to be the imageURL stored in state. 
- [x] make sure navbar photo changes when profile photo is edited

### 🧑‍⚕️ Clean Up

- [x] ... 
- [x] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
