### ISSUE TITLE
Feature: User can click on a photographers profile to view profile page

### ISSUE THREAD

**Issue by RobACurtis** [RobACurtis/final-project#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?
While on the explore page, the user will be able to click a photographers profile to view their person profile page. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user will be able to explore a a list of photographer profiles and be able to click anyone of them to view their personal profile page and photo gallery. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-05-30 at 11 31 31 AM](https://user-images.githubusercontent.com/96838616/171045151-de6a84ed-40f7-4deb-8303-8c27e56fafce.png)

![Screen Shot 2022-05-30 at 11 31 42 AM](https://user-images.githubusercontent.com/96838616/171045163-2d666c72-740a-4bcc-8cb9-6d912ad6e66d.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to ...
- [x] respond to get requests for images belonging to a certain userId
- [x] needs to return all images belonging to a user and users email, firstname, lastname and location. 
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component to ...
- [x] be a user profile page
- [x] needs to have a cover photo with the users first name, lastname, location, email and profile picture on top of it. 
- [x] needs to have a light navbar underneath the users info with only the photostream 
- [x] needs to have a gallery of all the images the user has uploaded and same functionality and design as the explore page 
gallery.
- [x] Update the explore-people component to make the user cards clickable
- [x] when the card is clicked, it will trigger a hash change event to the user page.
- [x] the user page will request for the data using the user id. 

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
