### ISSUE TITLE
Feature: User can create an account

### ISSUE THREAD

**Issue by RobACurtis** [RobACurtis/final-project#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

The user will be able to create their own account in the application. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The explore button on the home page will now be a sign in button and the user will be able to click that button to be taken to a form. If the user wants to explore with out signing up, they can click the explore link in the navbar. The user on the sign up form will have to complete the form and when completed submit the sign up button. From there, they will be taken back to the home page. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-05-30 at 11 36 51 AM](https://user-images.githubusercontent.com/96838616/171045703-a76f24a2-6a53-43ec-ad22-635f3707b3b1.png)
![Screen Shot 2022-05-30 at 11 36 57 AM](https://user-images.githubusercontent.com/96838616/171045707-408d20b6-6249-4a2b-b1a5-eb9a8e0160af.png)
![Screen Shot 2022-05-30 at 11 37 09 AM](https://user-images.githubusercontent.com/96838616/171045709-874dbec1-5674-4586-b579-7ac34384beb2.png)
![Screen Shot 2022-05-30 at 11 37 18 AM](https://user-images.githubusercontent.com/96838616/171045710-73a7a438-81ff-4a94-b887-ae7660dc9bc0.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to receive a post request to add a user
- [x]  needs to have all required parameters (username, password, email, location, firstname and lastName)
- [x]  needs to handle errors if a parameter is missing 
- [x]  need to implement argon2 to hash the password and only store the hashed password into database 
 - [x]  will insert new user into database 
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component to show a form for the sign up page. 
- [x] create a form and apply necessary styling to it.
- [x] it needs a field for username, firstname, lastname, email, location, and password.
- [x]  all fields are required. 
- [x]  on the submit event, the input values will be sent to the server as a post request to add the user to the database. 
- [x] the background image on the form page should be hidden in mobile view.
- [x]  when the form is submitted, the user will be sent back to the home page. 
- [x]  the explore button on the home page should be a sign up button now

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
