### ISSUE TITLE
Feature: User can log into account

### ISSUE THREAD

**Issue by RobACurtis** [RobACurtis/final-project#6]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

After signing up, the user will be able to log into their account.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When on the home page, there will be an option to log into account in the navbar. The user will be able to submit their username and password to sign into their account. They will be taken to their own profile page with a default profile and cover photo. There will be a user icon in the navbar to take them back to their profile page if they leave it. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-05-30 at 11 41 30 AM](https://user-images.githubusercontent.com/96838616/171046261-3b7c2e97-fbca-4a2d-ad6e-ec7ef7c7149d.png)
![Screen Shot 2022-05-30 at 11 41 21 AM](https://user-images.githubusercontent.com/96838616/171046262-12bce099-3bd9-4cea-b978-a5039fc554a1.png)
![Screen Shot 2022-05-30 at 11 41 14 AM](https://user-images.githubusercontent.com/96838616/171046263-a03ddcb8-eae7-423e-8d9b-5c8ab6ef8c4e.png)

![Screen Shot 2022-05-30 at 11 42 00 AM](https://user-images.githubusercontent.com/96838616/171046244-ae77a6a2-2b24-4be5-8c6d-7105e0bd4b2c.png)
![Screen Shot 2022-05-30 at 11 41 49 AM](https://user-images.githubusercontent.com/96838616/171046251-47e83afd-db9d-48a5-a9cd-25bcac2c920d.png)
![Screen Shot 2022-05-30 at 11 41 40 AM](https://user-images.githubusercontent.com/96838616/171046258-e4d79a44-c226-4935-96e3-7dc9bddf96f3.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to ...
- [x] create a post request route for sign-in.
- [x] this route will need to check for usename and password on the req.body
- [x] if missing one, it will need to send an error message
- [x] query the database for the userId and hashed password entered by the user
- [x] if missing, then send an error.
- [x] else it will check if the hashedpassword matches the password entered by the user
- [x] if it is, then it will create a payload object with userId and username.
- [x] it will created a token
- [x] it will send a response with an object containing the token and user.
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Update navbar component to have a log in button.
- [x] it will navigate to the #log-in page 
- [x] update sign-up page to navigate to log in page after signing up. 
- [x] update app.jsx to send a handleSignIn method as a prop.
- [x] this method will assign the token to local storage and set the state with the user object.
- [x] in componentDidMount in app.jsx check for a token in local storage, if true then use jwtDecode to get the user and set the state properties user.
- [x] Create a component for the user to sign in after signing up.
- [x] it will need to have a form with the same styling as sign up. it will only need username and password inputs.
- [x] on submit it will need to send a post request with the username and password with fetch
- [x] it will check the response for the user and token from the server.
- [x] if true, it will call the handlseSignIn method to assign the token to local storage and set the state in the home page with the user. 
- [x] the navbar component will also need to check if the user in state is truthy. If it is, the login button will now be a user 
icon 
- [x] the user icon will be a link to the users profile page. 

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
