### ISSUE TITLE
Feature: User can edit their profile image

### ISSUE THREAD

**Issue by RobACurtis** [RobACurtis/final-project#7]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

The user will be able to change their profile photo.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When the user created their account, they were given a photo for their profile account. The user will be able to hover over their profile image and click it. When it is clicked, a modal will appear with a form with a file input where they can change their profile photo after clicking the submit button. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-05-30 at 11 53 30 AM](https://user-images.githubusercontent.com/96838616/171047699-5d6dd833-ea3b-4b40-97d9-14ce62b93f33.png)
![Screen Shot 2022-05-30 at 11 53 37 AM](https://user-images.githubusercontent.com/96838616/171047704-2d35362f-a6f5-4df7-918a-55324e3e6a0c.png)
![Screen Shot 2022-05-30 at 11 55 12 AM](https://user-images.githubusercontent.com/96838616/171047705-77bc8dca-433d-4d3a-a4c8-350b9500d79d.png)
![Screen Shot 2022-05-30 at 11 55 24 AM](https://user-images.githubusercontent.com/96838616/171047709-b544ba89-9266-4c04-8e3e-8b9cdb6859d4.png)
![Screen Shot 2022-05-30 at 11 55 38 AM](https://user-images.githubusercontent.com/96838616/171047714-eb8c0062-3886-4695-8905-a2a44be25895.png)
![Screen Shot 2022-05-30 at 11 55 57 AM](https://user-images.githubusercontent.com/96838616/171047716-b9317f6b-a21e-4b8f-b194-505b26b66064.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Update `data.sql` to ...
- [x] Have updated filenames for the stock profile images based on a new directory for profile images.  

### ☁️ Server

- [x] Update server to have a folder called profile images.
- [x] add an uploads middle ware file to the server
- [x] install multer
- [x] the uploads middleware needs to store the image file in the proper directory and keep its original name and be passed as an argument in the post request.
- [x] create an authorization middleware.
- [x] it needs to get the token from the request header to confirm the user is who they say they are. 
- [x] user the middleware before the post request.
- [x] set up the route for the post request
- [x] it needs to create the correct imageUrl using the join method.
- [x] it needs to insert into the users table the new image url
- [x] it needs to send the result back to the client. 
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Update user profile page component to ...
- [x] have a button available when user hovers over their profile image to edit.
- [x] if the user clicks the button, a modal will appear with a file upload form.
- [x] the modal will interact with state to display and hide it. 
- [x] the upload button will need to send a post request with its access token to the server
- [x] when the response comes, state will be reset and the modal will be hidden. 

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
