### ISSUE TITLE
Feature: User can upload images to a gallery

### ISSUE THREAD

**Issue by RobACurtis** [RobACurtis/final-project#8]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

The user will be able to have their own photo gallery containing images they uploaded.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

While on their profile page, the user will be able to see a link to upload images. When they click the link, a modal will open with a file input. They can then upload their photo to the database. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-05-30 at 11 59 03 AM](https://user-images.githubusercontent.com/96838616/171048025-6bbd450c-b7b3-4bdb-a49a-181a83a3e078.png)
![Screen Shot 2022-05-30 at 11 59 23 AM](https://user-images.githubusercontent.com/96838616/171048027-532025ea-b370-4ed7-ba08-9760fc9f40dc.png)
![Screen Shot 2022-05-30 at 11 59 15 AM](https://user-images.githubusercontent.com/96838616/171048036-c9eb01de-4bd3-479a-a591-7efa8260c8be.png)
![Screen Shot 2022-05-30 at 11 59 31 AM](https://user-images.githubusercontent.com/96838616/171048038-bc4fd0ea-32ed-44c7-911d-4dc8f0581060.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] refractor uploads middleware to send images to the  gallery images directory.
- [x] Update `server/index.js` to ...
- [x] be able to respond to post requests for images specifically to image gallery.
- [x] needs to get the userId of the req user and create imageUrl from the req.file.filename
- [x] it will query the database to insert the new photo into the photos table, with the userId and the now() function.
- [x] make sure it sends the response with the new imageUrl and userId
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] create a component for uploading images to the gallery. It should be similar to the modal in edit profile image. 
- [x] update user profile page to have a link to open modal for uploading an image to a gallery..
- [x] this modal will need to send post requests to upload images to the DB and handle the response from the server.
- [x] when the user uploads photo, the modal will close. 

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
