### ISSUE TITLE
Feature: User can scroll infinitely in explore gallery

### ISSUE THREAD

**Issue by RobACurtis** [RobACurtis/final-project#9]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?
When exploring images the user can scroll infinitely and load more images along the way. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user can visit the explore page and view images. As they scroll to the bottom of the page, more images will load for them to continue scrolling. They will see images from newest to oldest. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-06-10 at 10 31 46 AM](https://user-images.githubusercontent.com/96838616/173120272-74de1b3f-f64b-4dd6-ac64-527d678c7a77.png)
![Screen Shot 2022-06-10 at 10 31 36 AM](https://user-images.githubusercontent.com/96838616/173120286-dd535537-1e45-4558-8b05-6a20e406f18a.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to ...
- [x] in the route for explore-images set an offset with the limit clause.
- [x] offset ([number of images already loaded])
- [x] limit 15
- [x] the route needs to be able to recieve different numbers for the offset. 
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Update photostream component to ...
- [x] set up an event listener on the window object for scroll. 
- [x] set up a function to be called on the scroll event.
- [x] set state to keep count of the length of the array.
- [x] in the new function, send a get request when the user scrolls to the bottom of the page with the number of currently 
loaded images in the array in state. 
- [x] When the response comes, the new images need to append to the bottom of the gallery.
- [x] the current images are first stored in state. 
- [x] push the new loaded image objects into the array and reset state. 
- [x] the render method will be called and the new images need to append to the current gallery
- [x] the user can then continue scrolling from the same place they left off. 
- [x] when the user reaches the bottom of the page again, another request will be sent and the process will repeat.  

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
